### ISSUE TITLE
Subdirectory support

### ISSUE THREAD

**Issue by mcechini** [orangewise/s3-zip#13]
It doesn't look like I'm able to generate a zip file that preserves an existing directory structure.  Is there a way to do that?

**Comment by orangewise** [comment]
Hmm, I have not tried that yet. Maybe you can create a PR? That would be awesome.

**Comment by rutkowskib** [comment]
Hi,

I managed to do exactly that, but i had to change code of s3-files package(just 1 line of code). Maybe you will be interested in forking it with my code(or some other solution)  to add this functionality to your library

**Comment by orangewise** [comment]
Sure, please create a PR with the change. I'm happy to review it.

**Comment by rutkowskib** [comment]
I have created pull requests
For s3-files: https://github.com/orangewise/s3-files/pull/12
For s3-zip https://github.com/orangewise/s3-zip/pull/19
