### ISSUE TITLE
Add more detailed msgs.

### ISSUE THREAD

**Issue by skghosh-invn** [orangewise/s3-zip#14]
I am getting the msg:
NoSuchKey: The specified key does not exist.

Not sure where is this coming from. Can you please a little more description.

**Comment by orangewise** [comment]
Hi @skghosh-invn, it would be nice if you would add a test case or something. I have no clue how you are using this module...

**Comment by skghosh-invn** [comment]
Hi @orangewise I am using the example from a forever process. Once the files processing is completed then I am adding it to a zip on S3.

**Comment by ravishan110** [comment]
i am facing the same issue, `NoSuchKey: The specified key does not exist.` . All the files are present in the s3 bucket, still I am getting this error. Please Help.
