### ISSUE TITLE
Need help in integrating s3-zip on [Error: append: queue closed]

### ISSUE THREAD

**Issue by skghosh-invn** [orangewise/s3-zip#16]
Hi @orangewise,

I am using s3-zip to to zip the files without downloading so that this can be converted to a Lambda Function if needed. Please let me know whatever looks wrong below as I am new to node.js

Right now I am getting the error: `append: queue closed`
```
archive error [Error: append: queue closed]

/home/<<userid>>/node_modules/s3-zip/s3-zip.js:25
    throw err
          ^
Error: append: queue closed
```

The code I am using to test on the command line using the `node` interpreter is as below. The MyFile.zip is not present in s3.
```
const AWS = require('aws-sdk');
const path = require('path');
const s3Zip = require('s3-zip');
const awsRegion = '<<MyRegion>>';
const dataBucket = "<<MyBucketNameGoesHere>>";
const srcKey = "<<Testing With a Static Path to an Object>>";
const srcFile = path.basename(srcKey);
const srcFolder = path.dirname(srcKey);

var zipFileBody = s3Zip.archive({ region: awsRegion, bucket: dataBucket}, srcFolder + '/', [srcFile]);
var zipParams = { params: { region: awsRegion, Bucket: dataBucket, Key: path.join(srcFolder,'MyFile.zip') } };
var zipFile = new AWS.S3(zipParams);

zipFile.upload({Body: zipFileBody}).on('httpUploadProgress', function (evt) {
            console.log(evt)
        }).send(function (e, r) {
            if (e) {
                var err = 'zipFile.upload error ' + e;
                console.log(err);
            }
            console.log(r);
        })
```

Couple of questions here:
1. How does s3-zip add the .zip-file s3 when it is not present?
2. Are new files are presented to an existing .zip-file on s3 appended?
3. When files presented to the existing .zip-file on s3 are already present are they overwritten?

**Comment by orangewise** [comment]
Hi @skghosh-invn, please start with the example in the readme. s3Zip.archive does not return a zip file, it returns a stream that should be piped into a file...
