### ISSUE TITLE
File not exist exception is not handled

### ISSUE THREAD

**Issue by navjotdhanawat** [orangewise/s3-zip#17]
I am downloading multiple files by passing an array of the file paths. Suppose a file from array not exist, it will break execution.
It is returning following error:
Code: 'NoSuchKey',
Message: 'The specified key does not exist.'

**Comment by orangewise** [comment]
Hi, the module assumes your using paths that exist... Before zipping you can query your bucket. There is an example in the readme.

**Comment by ravishan110** [comment]
@navjotdhanawat Can you tell me how you are using it? I am getting the same error `NoSuchKey: The specified key does not exist`, even if the files are present in the s3 Bucket. If you can provide me the code, it would be very helpful.

**Comment by ravishan110** [comment]
@orangewise How to query the bucket to check if the file exists in s3? I am not able to find any similar example in the redme. Please help.

**Comment by orangewise** [comment]
Hi, why don't you try this example in the readme:

https://github.com/orangewise/s3-zip#zip-a-whole-bucket-folder

You can use the AWS sdk to query your bucket and find out what objects are in there.
