### ISSUE TITLE
The zip file will be overridden

### ISSUE THREAD

**Issue by quoc1506** [orangewise/s3-zip#21]
I'm using AWS Lambda to append the files to zip file, and this function be executed when someone upload a file.
It's mean when someone upload a file, this file will be appended to current zip file (create new one if not exist), so the zip file will have a mutiple files from mutiple users.
That's my expect.
But actually,  when someone upload a file, this file be appended to zip file, and override to existed zip file, that's mean the zip file always only has one newest upload file.
Could you give a solution?
Here is the code I used: https://github.com/orangewise/s3-zip/blob/HEAD/aws_lambda.md

**Comment by orangewise** [comment]
Appending to an existing zip is not supported.
