### ISSUE TITLE
[lambda] NoSuchKey: The specified key does not exist.

### ISSUE THREAD

**Issue by Parkseokje** [orangewise/s3-zip#26]
For lambda, why use `zipFile.upload` without using createWriteStream or something?

**Payload:**

`{
    "folder": "images-resized",
    "files": [
        "1511414734320.300",
        "1511415403861.600"
    ]
}`

**Key:**

`images-resized/download.zip`

**On upload error occurs:**
`2017-11-23T11:31:48.878Z	e3434ea3-d041-11e7-a539-a50787a2ff84	NoSuchKey: The specified key does not exist.
at Request.extractError (/var/task/node_modules/aws-sdk/lib/services/s3.js:577:35)
at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
at Request.emit (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
at Request.emit (/var/task/node_modules/aws-sdk/lib/request.js:683:14)
at Request.transition (/var/task/node_modules/aws-sdk/lib/request.js:22:10)
at AcceptorStateMachine.runTo (/var/task/node_modules/aws-sdk/lib/state_machine.js:14:12)
at /var/task/node_modules/aws-sdk/lib/state_machine.js:26:10
at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:38:9)
at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:685:12)
at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:115:18)`

**My Lambda handle:**.

```console.log('Loading...')

const aws = require('aws-sdk')
const s3Zip = require('s3-zip')
const bucket = process.env.AWS_BUCKET_NAME;
const region = 'ap-northeast-2'

exports.handle = (event, context, callback) => {
  console.log('Received event:', JSON.stringify(event, null, 2));

  const {
    folder,
    files,
    zipFileName = 'download.zip'
  } = event

  try {
    const body = s3Zip.archive({
      region, bucket
    }, folder, files)

    const zipFile = new aws.S3({
      apiVersion: '2012-10-17',
      Bucket: bucket,
      region: region,
      Key: `${folder}/${zipFileName}`
    })

    console.log('zipFile:', zipFile)

    zipFile.upload({ Body: body })
      .on('httpUploadProgress', (event) => {
        console.log(event)
      })
      .send((err, result) => {
        if (err) {
          console.log('zipFile.upload error:', err)
          callback(err)
        } else {
          callback(null, result)
        }
      })
  } catch (err) {
    console.log('catched error:', err)
    callback(err)
  }
}```

**Comment by orangewise** [comment]
What is the question?

**Comment by Parkseokje** [comment]
`The specified key does not exist error` error From Lambda is the problem I was trying to solve.
Do you know why this is happening? 
And one more thing .. 
I don't understand the portion of `zipFile.upload ... sending`. Could you please explain briefly?

**Comment by orangewise** [comment]
`The specified key does not exist error` -> you are trying to zip a file that is not there...
`zipFile.upload` -> puts the zip file into s3: http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#upload-property

**Comment by AndrewSouthpaw** [comment]
For those of you who got hung up on this problem like me... the `folder` param *requires a trailing slash*.

```js
{ folder: 'myFolder' } // bad times
{ folder: 'myFolder/' } // good times
```
