### ISSUE TITLE
Lambda function

### ISSUE THREAD

**Issue by Phlongs** [orangewise/s3-zip#27]
Concerning var body = s3Zip.archive({ region: region, bucket: bucket}, folder, files) this is what the function is returning for me: 
Archiver {
  options:
   { highWaterMark: 1048576,
     statConcurrency: 4,
     comment: '',
     forceUTC: false,
     store: false,
     zlib: { level: 1 },
     forceZip64: false,
     forceLocalTime: false },
  _readableState:
   ReadableState {
     objectMode: false,
     highWaterMark: 1048576,
     buffer: BufferList { head: null, tail: null, length: 0 },
     length: 0,
     pipes: null,
     pipesCount: 0,
     flowing: null,
     ended: false,
     endEmitted: false,
     reading: false,
     sync: false,
     needReadable: true,
     emittedReadable: false,
     readableListening: false,
     resumeScheduled: false,
     destroyed: false,
     defaultEncoding: 'utf8',
     awaitDrain: 0,
     readingMore: false,
     decoder: null,
     encoding: null },
  readable: true,
  domain: null,
  _events:
   { end: { [Function: bound onceWrapper] listener: [Function: onend] },
     prefinish: { [Function: bound onceWrapper] listener: [Function] },
     unpipe: [Function: onunpipe],
     drain: [Function],
     error: [ [Function: onerror], [Function] ],
     close: { [Function: bound onceWrapper] listener: [Function: onclose] },
     finish: { [Function: bound onceWrapper] listener: [Function: onfinish] } },
  _eventsCount: 7,
  _maxListeners: undefined,
  _writableState:
   WritableState {
     objectMode: false,
     highWaterMark: 1048576,
     finalCalled: false,
     needDrain: false,
     ending: false,
     ended: false,
     finished: false,
     destroyed: false,
     decodeStrings: true,
     defaultEncoding: 'utf8',
     length: 0,
     writing: false,
     corked: 0,
     sync: true,
     bufferProcessing: false,
     onwrite: [Function],
     writecb: null,
     writelen: 0,
     bufferedRequest: null,
     lastBufferedRequest: null,
     pendingcb: 0,
     prefinished: false,
     errorEmitted: false,
     bufferedRequestCount: 0,
     corkedRequestsFree: CorkedRequest { next: null, entry: null, finish: [Function] } },
  writable: true,
  allowHalfOpen: true,
  _transformState:
   TransformState {
     afterTransform: [Function],
     needTransform: false,
     transforming: false,
     writecb: null,
     writechunk: null,
     writeencoding: null },
  _format: 'zip',
  _module:
   Zip {
     options:
      { highWaterMark: 1048576,
        statConcurrency: 4,
        comment: '',
        forceUTC: false,
        store: false,
        zlib: [Object],
        forceZip64: false,
        forceLocalTime: false },
     supports: { directory: true, symlink: true },
     engine:
      Transform {
        options: [Object],
        _readableState: [Object],
        readable: true,
        domain: null,
        _events: [Object],
        _eventsCount: 4,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: true,
        allowHalfOpen: true,
        _transformState: [Object],
        offset: 0,
        _archive: [Object],
        _entry: null,
        _entries: [] } },
  _pending: 0,
  _pointer: 0,
  _entriesCount: 0,
  _entriesProcessedCount: 0,
  _fsEntriesTotalBytes: 0,
  _fsEntriesProcessedBytes: 0,
  _queue:
   { _tasks: DLL { tail: null, head: null, length: 0 },
     concurrency: 1,
     payload: 1,
     saturated: [Function: noop],
     unsaturated: [Function: noop],
     buffer: 0.25,
     empty: [Function: noop],
     drain: [Function: bound ],
     error: [Function: noop],
     started: false,
     paused: false,
     push: [Function: push],
     kill: [Function: kill],
     unshift: [Function: unshift],
     remove: [Function: remove],
     process: [Function: process],
     length: [Function: length],
     running: [Function: running],
     workersList: [Function: workersList],
     idle: [Function: idle],
     pause: [Function: pause],
     resume: [Function: resume] },
  _statQueue:
   { _tasks: DLL { tail: null, head: null, length: 0 },
     concurrency: 4,
     payload: 1,
     saturated: [Function: noop],
     unsaturated: [Function: noop],
     buffer: 1,
     empty: [Function: noop],
     drain: [Function: noop],
     error: [Function: noop],
     started: false,
     paused: false,
     push: [Function: push],
     kill: [Function: kill],
     unshift: [Function: unshift],
     remove: [Function: remove],
     process: [Function: process],
     length: [Function: length],
     running: [Function: running],
     workersList: [Function: workersList],
     idle: [Function: idle],
     pause: [Function: pause],
     resume: [Function: resume] },
  _state:
   { aborted: false,
     finalize: false,
     finalizing: false,
     finalized: false,
     modulePiped: true },
  _streams: [] }

**Comment by orangewise** [comment]
And your question is?

**Comment by Phlongs** [comment]
Sorry, am I passing the data correctly relative to what the function is returning back?  I am also receiving this error: NoSuchKey: The specified key does not exist.  Thanks for the help!

**Comment by Phlongs** [comment]
I guess to simplify the question, when does s3-zip write the new zip file object to the s3 bucket?

**Comment by Phlongs** [comment]
Got it to work, you can close this issue

**Comment by anujgeek** [comment]
How do I get raw data of this stream? I want to use this with Azure Function. Here's what I'm trying to use:
`let body = s3Zip.archive({ region: region, bucket: bucket }, folder, [file, file]);
    context.res = {
        status: 200,
        headers: {
            "Content-Type": "application/zip"
        },
        isRaw: true,
        body
    };
    context.done();`

**Comment by rad182** [comment]
@Phlongs not sure how did you get it to work?
I'm trying to upload to s3 using lambda also but for some reason it's not uploading
