### ISSUE TITLE
S3 no such key in root bucket 

### ISSUE THREAD

**Issue by christopherABM** [orangewise/s3-zip#29]
Hi, I use your AWS lambda function to zip files, but I have an issue when I try to zip a file list, all the files are in the root `s3://bucket_name/ ` and I have tried in other buckets with folders and it works ok. However ,I am not sure if the issue is the folder name, here is my code
```
$payload = json_encode([
            'region'            => AWS_REGION,
            'sourceBucket'      => 'SOURCE_BUCKET',
            'destinationBucket' => ZIP_BUCKET,
            'folder'            => '/',
            'files'             => $files ,
            'zipFileName'       => 'zip_name.zip'
        ]);
```
I appreciate your help. Thanks

**Comment by orangewise** [comment]
Hi @christopherABM, this is a use case that I haven't tried... Maybe you can adjust the code and create a PR? I'm happy to merge.
