### ISSUE TITLE
zip entire S3 folder?

### ISSUE THREAD

**Issue by etinif** [orangewise/s3-zip#3]
Hello,

Is there a way to zip an entire s3 folder without specifying individual file names?

**Comment by orangewise** [comment]
Hi @etinif 

I have added an example that shows how to do this:

https://github.com/orangewise/s3-zip#zip-a-whole-bucket-folder

Hope it helps :)

**Comment by dekel31** [comment]
This won't work with a folder of more than 1000 items, right? (listObjects gives 1k top)

**Comment by orangewise** [comment]
You can always loop...
