### ISSUE TITLE
Error : EROFS: read-only file system

### ISSUE THREAD

**Issue by souuu** [orangewise/s3-zip#30]
Hello,
I'm trying to work with s3-zip to zip some files in s3 bucket using a lambda function.
when I do,
```
function zip(files) {
console.log(files)
var output = fs.createWriteStream(join(__dirname, 'use-s3-zip.zip'))
s3Zip
.archive({ region: region, bucket: bucket, preserveFolderStructure: true }, folder, files)
.pipe(output)
}
```
in cloudwatch, I have a successful console.log of the files
in the next line I have : 
```
Error: EROFS: read-only file system, open '/var/task/use-s3-zip.zip'
at Error (native)
```

Any help please ?

**Comment by sleman** [comment]
Maybe create the file in the `/tmp` directory.

**Comment by orangewise** [comment]
Yes, try the `/tmp` folder or zip to s3.

**Comment by kelenakamura** [comment]
is there an example of saving to the /tmp folder and having that auto download in the users browser?
