### ISSUE TITLE
Express Example?

### ISSUE THREAD

**Issue by alexminnaar** [orangewise/s3-zip#34]
I am new to Node and I was wondering if s3-zip works within the express framework.  Specifically, I would like to send the zipped file back to the client using the express framework. If this is possible it would be great if you could provide an example.  Thanks

**Comment by mohuk** [comment]
Hey @alexminnaar 

Yes it does work on any framework that is compatible with streams including express. Here is a short example

```
const s3Zip = require('s3-zip');

app.get('/download', (req, res) => {
    s3Zip.archive({ region: region, bucket: bucket }, '', 'abc.jpg').pipe(res);
});
```

Above should stream out the file in the response of the request. Hope this helps.

**Comment by orangewise** [comment]
thanks for giving the example @mohuk

**Comment by alignsoft** [comment]
This would be incredibly useful to include on the examples page, as this was the missing piece I struggled with for hours yesterday.

**Comment by orangewise** [comment]
Please add your example to the readme, will merge it asap...

**Comment by davidtonkindiffgrav** [comment]
> Hey @alexminnaar
> 
> Yes it does work on any framework that is compatible with streams including express. Here is a short example
> 
> ```js
> const s3Zip = require('s3-zip');
> 
> app.get('/download', (req, res) => {
>     s3Zip.archive({ region: region, bucket: bucket }, '', 'abc.jpg').pipe(res);
> });
> ```
> 
> Above should stream out the file in the response of the request. Hope this helps.

Hi, I am trying this on my server. I have a file called test.png in the root of the bucket I am accessing and it has read permissions.
But Im getting this Error: 

```
TypeError: keys.forEach is not a function
    at Object.s3Files.createKeyStream (F:\webdev\projects\vcs-api\node_modules\s3-files\s3-files.js:29:8)
    at Object.s3Zip.archive (F:\webdev\projects\vcs-api\node_modules\s3-zip\s3-zip.js:29:33)
    at F:\webdev\projects\vcs-api\server.js:1004:6
    at Layer.handle [as handle_request] (F:\webdev\projects\vcs-api\node_modules\express\lib\router\layer.js:95:5)
    at next (F:\webdev\projects\vcs-api\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (F:\webdev\projects\vcs-api\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (F:\webdev\projects\vcs-api\node_modules\express\lib\router\layer.js:95:5)
    at F:\webdev\projects\vcs-api\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (F:\webdev\projects\vcs-api\node_modules\express\lib\router\index.js:335:12)
    at next (F:\webdev\projects\vcs-api\node_modules\express\lib\router\index.js:275:10)
```
Am I missing something ?

Ta

**Comment by seanmurph** [comment]
> But Im getting this Error:
> 
> ```
> TypeError: keys.forEach is not a function
>     at Object.s3Files.createKeyStream (F:\webdev\projects\vcs-api\node_modules\s3-files\s3-files.js:29:8)
> ```
> 
> And this is my Code:
> 
> ```
> var  s3Zip   = require('s3-zip');
> const bucketName = "myBucket";
> 
>  app.get('/zip', (req, res) => {
>   s3Zip
>     .archive({ region: 'ap-southeast-2', bucket: bucketName },  '', 'test.png')
>     .pipe(res)
> })
> ```
> 
> Am I missing something ?
> 
> Ta

@davidtonkindiffgrav The last argument to `.archive()` should be an array:

```
    .archive({ region: 'ap-southeast-2', bucket: bucketName },  '', ['test.png'])
```

If this example does get added to the README we'd want to change that.

Also, you should use `res.attachment()` (http://expressjs.com/en/api.html#res.attachment) to properly inform the browser to download the file rather than attempt to render it inline.
