### ISSUE TITLE
Zip multiple files from different folder

### ISSUE THREAD

**Issue by binoperez** [orangewise/s3-zip#38]
Can I zip multiple files from different folder?

for example I want to zip file_a, file_b and file_c from this sample folder structure.

mys3bucket
     -root_folder
           -folder_1
                  -file_a
           -folder_2
                   -file_b
           -folder_3
                    -file_c

![folders](https://user-images.githubusercontent.com/25294018/40023662-73596a96-5791-11e8-8725-9f9f6adb9931.JPG)

thanks!

**Comment by orangewise** [comment]
hi, this is currently not supported....

**Comment by gaurav16694** [comment]
@orangewise  when we can have that feature ?

**Comment by rokumatsumoto** [comment]
> hi, this is currently not supported....

hi @orangewise,
if we use [custom paths](https://github.com/orangewise/s3-zip#organize-your-archive-with-custom-paths-and-permissions), will it work? or should i use [direct urls](https://github.com/orangewise/s3-zip/issues/49#issue-419266302) for files array?

Thanks!

**Comment by stolarczyk** [comment]
What you can do is prepend the desired folder names to corresponding file names and leave the folder argument out, for example:

```typescript
const files = [{ "fileId": "1", "name": "test.txt" }, { "fileId": "2", "name": "test2.txt" }]
s3Zip.archive({ region: region, bucket: bucket, debug: true }, '', files.map(file => `${file.fileId}/${file.name}`)).pipe(res)
```
