### ISSUE TITLE
Files unzip to .zip.cpgz format on mac

### ISSUE THREAD

**Issue by Pterobyte** [orangewise/s3-zip#39]
I'm able to download s3 files into a local folder successfully, until the extraction process always returns a file.zip.cpgz, which unzips to file.zip, and vice-versa. 

Unzipping from my command line via `unzip file.zip` reveals the undamaged files, so I'm wondering if there's a problem with the zipping process in this package.

In the meantime let me know if there's a workaround, thanks!

**Comment by orangewise** [comment]
I've not seen this behaviour. Maybe @mhemrg knows about this?

**Comment by mhemrg** [comment]
@Pterobyte Are you downloading the zip file with a browser?
Have you compressed the file with `gzip` option?

**Comment by Pterobyte** [comment]
Tried the gzip option, but the results are the same:
```
s3Zip
    .setArchiverOptions({ gzip: true })
    .archive({ region, bucket }, 'test/', eventsArray)
    .pipe(output('files/', 'audio.zip'));
```

![image](https://user-images.githubusercontent.com/23695312/40091334-97d47ccc-58e9-11e8-8a0d-300c5d0466b6.png)
