### ISSUE TITLE
Add other files to zip

### ISSUE THREAD

**Issue by jneljneljnel** [orangewise/s3-zip#46]
is it possible to add other files to the zip that are not in s3?  I have an api endpoint below that works well to fetch the files I need from s3. but, I also need to send one file called 'config.json along with the zip. is this possible to do? 

```
router.get('/test1', (req, res, next) => {
  Files.find().then(results => {
      let fileList = results.map(x => x.name + '.wav')
      let folderList = results.map(x => { return { name: 'files/audio/' + x.name + '.wav'}})
      let stream = s3Zip
        .archive({ s3: s3, bucket: bucket, debug: true }, '', fileList, folderList)
        .pipe(res)
  })
})
```

**Comment by orangewise** [comment]
Don't think you can do it out of the box...

**Comment by mebibou** [comment]
@jneljneljnel did you find a solution to your problem?
