### ISSUE TITLE
Fails to complete on missing or bad key

### ISSUE THREAD

**Issue by ajmcgarry** [orangewise/s3-zip#47]
Pass a set of keys to the archive function with a bad key purposely included.
The debug log continues to download everything but the failure prevents the file being ended and closed.
I believe the issue is actually in your s3-files library.

A bad key could happen in the event that a object is deleted from S3 before it can be streamed.

**Comment by orangewise** [comment]
Please submit a PR...

**Comment by Dolaned** [comment]
is this still needed cause its something i need.
