### ISSUE TITLE
Can s3-zip be used with express.js?

### ISSUE THREAD

**Issue by jacobokoenig** [orangewise/s3-zip#48]
Hi,

I'm trying to send the zip file with a response on a http request. I see nothing that hints to this being available in the README, but was wondering if it was possible at all as I have found no other dependencies to achieve this.

Here is my slight adaptation to the code:

app.get('/files', (request, response) => {
  const objectIds = request.body.objectIds
  const folder = request.body.folder

  response.set('content-type', 'application/zip')

  s3Zip
    .archive({ s3: s3, bucket: aws_bucket_name }, folder, objectIds)
    .pipe(response)

  s3Zip.on('end', () => {
    console.log('ended');
    response.end();
  })
});

**Comment by orangewise** [comment]
Hi @jacobokoenig, this is a similar question: https://github.com/orangewise/s3-zip/issues/45
