### ISSUE TITLE
Zipping files from AWS via array of presigned URLs

### ISSUE THREAD

**Issue by alignsoft** [orangewise/s3-zip#49]
I have a library of images on AWS in a protected bucket, and want to be able to serve(stream) a subset of them as a zip download in response to a GET request.

I can identify the files for the request, generate an array of preSigned URLs and a corresponding array of the file names that match, but cannot for the life of me figure out how to leverage s3-zip to fetch these files via their preSigned URLs into a Zip file and stream that back to the requestor.

Is this possible?

My understanding of the AWS example here is that it assumes the bucket is public, and you can pass the bucket, folder name etc. and fetch the files.

I'm not sure if I'm overcomplicating things by getting preSigned URLs for all the files, but I don't see any option to do that any other way.

Any guidance would be very much appreciated. 

The following code is stripped to only the relevant bits:

```
exports.getDownloads = (req, res, next) => {

fileList = [
  'https://the-archive-name.s3.us-east-2.amazonaws.com/media/originals/588f26a61b772-raw.jpg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIA...-Amz-Expires=300&X-Amz-Signature=...-Amz-SignedHeaders=host',
  'https://the-archive-name.s3.us-east-2.amazonaws.com/media/originals/5bb37fc4ad871-raw.jpg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIA...-Amz-Expires=300&X-Amz-Signature=...-Amz-SignedHeaders=host',
]```

The fileList is fetched, authenticated, and the above array of preSigned URLs passed to the Zip stream - the above is just a sanitized example of the console.log output.

```
    const region = 'us-east-2'
    const bucket = 'the-archive-name'
    const folder = 'media/originals/'
```
The folder seems redundant here as the images all have full signed URLs

```
            const output = fs.createWriteStream(join(__dirname, 'Archive-Images.zip'))

            s3Zip
              .archive({ region: region, bucket: bucket}, '', fileList)
              .pipe(output)

```

What I'm expecting is that the user hits the getDownloads endpoint, which fetches their images from AWS, compiles them into a single 'Archive-Images.zip' file and starts streaming that zip to their local machine without writing it into the file system or having to generate the entire zip in memory first.

**Comment by orangewise** [comment]
Hi @alignsoft, s3-zip does not need a public bucket. You can fetch your files using your aws credentials, and then zip the files on your server before sending them to the the client. Or you can use a lambda to do the zipping and then send the zip file to the user with a signed url.
