### ISSUE TITLE
Memory concerns

### ISSUE THREAD

**Issue by glennfu** [orangewise/s3-zip#5]
Hi there! I've written an AWS Lambda function for the purpose of taking a list of files and adding them to a zip. You can see it here: https://gist.github.com/glennfu/5d95605fa56296d9dc056f5e7887beae

It's doing very little beyond the example you provided here: https://github.com/orangewise/s3-zip/blob/master/aws_lambda.md

I discovered that the memory usage is way higher than I expected. Here's some testing:

Files | Total Size | Memory Used | Zipped Size
------|------------|-------------|------------
2 | 30mb | 90mb | 138kb
3 | 15mb | 90mb | 69kb
5 | 75mb | 221mb | 344kb

I was really hoping to find that it could stream/pipe the files as it loaded them, unloading old files as each gets processed. Do you have any suggestions or ideas for how to improve this?

**Comment by orangewise** [comment]
Hi @glennfu, I'm not sure if I can think of an improvement at the moment, please let me know if you find a way...
