### ISSUE TITLE
AWS lamda zip file size limits

### ISSUE THREAD

**Issue by openstepmedia** [orangewise/s3-zip#58]
Quick question about your AWS lambda example.  I wasn't able to tell from the AWS documentation what is the maximum size that the resulting zip file can be.  

What is your experience with s3-zip? Will the lambda function crash if the resulting .zip file is over 2GB? More? Less?

Thanks!

**Comment by orangewise** [comment]
Have not tried this myself but maybe you can stream directly to s3...
