### ISSUE TITLE
net::ERR_INCOMPLETE_CHUNKED_ENCODING 200 (OK)

### ISSUE THREAD

**Issue by Anshul-SA** [orangewise/s3-zip#59]
Hi,
When I have files more then 100 in my s3 bucket. it takes lot of time and in frontend I get this error:"net::ERR_INCOMPLETE_CHUNKED_ENCODING 200 (OK)". Please assist. 
Thanks in advance

**Comment by orangewise** [comment]
You can try to increase your lambda’s memory, and/or the the timeout.

**Comment by Anshul-SA** [comment]
@orangewise I am using express js, from where I can give timeout?

**Comment by orangewise** [comment]
Ok, I thought you were using a lambda...

**Comment by gaurav16694** [comment]
`Connection timed out after 120000ms`
I am getting this error even my lambda memory is 2560 MB and timeout is set to 15 min @orangewise
