### ISSUE TITLE
DeprecationWarning

### ISSUE THREAD

**Issue by spotnape** [orangewise/s3-zip#61]
Simply importing the most recent version of s3-zip for an AWS Lambda, gives me the following warning in the CloudWatch logs.
`ERROR	(node:7) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.`

**Comment by orangewise** [comment]
Hi @spotnape, thanks for reporting. I'm using node 8.10 but do not have the issue. Are you sure it is related to `s3-zip`?
