### ISSUE TITLE
Subfolders in Windows

### ISSUE THREAD

**Issue by abalsekar** [orangewise/s3-zip#62]
Great module, but wasn't working for me for any content in subfolders under the root bucket. I'm developing on Windows, deploying on Linux.

Seems that the full paths returned by the s3Files.createKeyStream method in s3-files.js are platform dependent. I'm sure they should always be forward slashes (as used by S3).

I added a line to correct the slashes 
paths = paths.map(path => path.replace(/\\/g,"/")); 
just before the return streamify(paths) around line 36.

Not your bug - but hope this helps someone. Perhaps mention in the README??

**Comment by orangewise** [comment]
Hi @abalsekar, thanks for reporting. I've patched s3-files (2.0.1). Can you try if this solves the issue?

Appreciate your help.

**Comment by abalsekar** [comment]
Yes - fixed. Thanks.

Best,

AB.
