### ISSUE TITLE
Loading forever when specified file doesn't exist

### ISSUE THREAD

**Issue by cyril94440** [orangewise/s3-zip#67]
Hi there,
Thanks for your awesome library!!
I have an annoying issue, when for some reasons I have a wrong filename (S3 Key), it is loading forever! Is there any way to try catch error or abort if something is wrong?

Thank you very much!

**Comment by orangewise** [comment]
Hi @cyril94440, thanks for your feedback. The module currently assumes the objects are there. If you can create a patch, I'm happy to merge.
