### ISSUE TITLE
Change file names  before archiving

### ISSUE THREAD

**Issue by baodoan** [orangewise/s3-zip#70]
Hi,

Thanks for your helpful library. However, I wondering if there is a way that I can modify the original file names to somethings else before I zip the file and upload to S3. 

Thank you!

**Comment by orangewise** [comment]
Not sure if this can help: https://github.com/orangewise/s3-zip/blob/master/README.md#organize-your-archive-with-custom-paths-and-permissions

**Comment by baodoan** [comment]
I was able to figure it out. Yes, that was the solution. Thanks a lot for
your response and the library.

Best,
Bao
