### ISSUE TITLE
Examples in README.md use XmlStream unnecessarily 

### ISSUE THREAD

**Issue by davetapley** [orangewise/s3-zip#78]
The docs show `XmlStream` being used to build a `filesArray`:

https://github.com/orangewise/s3-zip/blob/1c21f8206a61047911e8a4fb2e1d9116c7e47953/README.md#L92-L101

---

But `aws-sdk` returns JS objects automatically, e.g:

```
  const {Contents} = await s3.listObjects(params).promise()
  const keys = Contents.map(({Key}) => Key
```

So why do we need `XmlStream`?

**Comment by orangewise** [comment]
I’ve not tested this part myself. Maybe you can add a test and update the readme? I’m happy to merge a PR.
