### ISSUE TITLE
Doesn't work with new AWS JS SDK v3

### ISSUE THREAD

**Issue by ffxsam** [orangewise/s3-zip#82]
The new v3 SDK is very picky about passing a `Readable` or `ReadableStream` into the `Upload` constructor:

https://github.com/aws/aws-sdk-js-v3/blob/b07e71986817d7781e12d9b687532c58d5ea6ba0/lib/storage/src/data-chunk/yield-chunk.ts#L15-L32

Is there some way to get a `Readable` from the `Archiver` instance that's returned by `s3Zip.archive()`?

**Comment by ffxsam** [comment]
My workaround for now is to use `ReadableStreamClone` (https://github.com/levansuper/readable-stream-clone) to clone the archiver instance, which results in a workable `Readable` instance. Not pretty, but it works.

**Comment by shriah** [comment]
I am doing something like this. 
``` 
  const pass = new stream.PassThrough();
  const paralellUploads3 = new Upload({
    client: s3Client,
    leavePartsOnError: false,
    params: {
      ...bucketParams,
      Key: key,
      Body: pass,
    },
  });
  archive.pipe(pass);
```
Initially thought of using this library but ended up writing my own util using the AWS JS SDK v3 and Archiver
