### ISSUE TITLE
Is there a way to put multiple s3 folders in the zip file?

### ISSUE THREAD

**Issue by zainulabd786** [orangewise/s3-zip#84]
I tried passing an array with folders paths but getting an 404 NoSuchKey error.
here's my sample code

`s3Zip
  .archive({ region: region, bucket: bucket}, [folder1, folder2], [file1, file2, file3, file4])
  .pipe(res)`

**Comment by lluisemper** [comment]
@zainulabd786 did you solve this issue?

**Comment by zainulabd786** [comment]
No, I used [Archiver](https://www.npmjs.com/package/archiver) instead.
