### ISSUE TITLE
Losing mime type and directory structure of zipped folders

### ISSUE THREAD

**Issue by askdesigners** [orangewise/s3-zip#9]
Is it somehow possible to preserve the structure of folders that contain other folders and files? Also it seems that files without a file extension are losing their mime types upon unzipping. Is there a work around for this? Great work on the module btw. :)

**Comment by orangewise** [comment]
The mime type is stored in s3's metadata, I'm not sure you can use that when unzipping...

I have not worked with nested objects, a PR is welcome though 😉
